FROM python:3.8-slim

RUN useradd bins

WORKDIR /home/bins

COPY requirements.txt requirements.txt
COPY main.py main.py

RUN apt-get update -q \
    && apt-get install -y gcc \
    g++ 

RUN pip install -r requirements.txt


COPY main.py main.py
RUN chmod +x main.py

CMD [ "python", "./main.py" ]